#!/bin/bash

comando
setprogress 7 "Atualizando sistema"
comando 1
setprogress 8
comando 2
setprogress 9
comando 3
setprogress 11
comando 4
setprogress 15 "Aguardando atualização"
comando 5
setprogress 33 "Configurando os pacotes instalados"
comando 6
setprogress 51 "Realizando upgrade"
comando 7
setprogress 62 "Removendo arquivos temporários"
comando 8
setprogress 78 "Realizando cleanup"
comando ...
setprogress 94 "Finalizando a instalação"
comando n
